{
    "meals": [
        {
            "idMeal": "52796",
            "strMeal": "Chicken Alfredo Primavera",
            "strMealAlternate": null,
            "strCategory": "Chicken",
            "strArea": "Italian",
            "strInstructions": "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and a pinch of pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through.  While the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with a few generous pinches of kosher salt. Add the pasta and give it a stir. Cook, stirring occasionally, until al dente, about 12 minutes. Reserve 1/2 cup of  pasta water before draining the pasta.  Remove the chicken from the pan and transfer it to a cutting board; allow it to rest. Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken. Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning). Cook, stirring often, until the veggies are tender, about 5 minutes. Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute.  Deglaze the pan with the white wine. Continue to cook until the wine has reduced by half, about 3 minutes. Stir in the milk, heavy cream, and reserved pasta water. Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes. Turn off the heat and add the Parmesan cheese and cooked pasta. Season with salt and pepper to taste. Garnish with Parmesan cheese and chopped parsley, if desired. ",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
            "strTags": "Pasta,Meat,Dairy",
            "strYoutube": "https://www.youtube.com/watch?v=qCIbq8HywpQ",
            "strIngredient1": "Butter",
            "strIngredient2": "Olive Oil",
            "strIngredient3": "Chicken",
            "strIngredient4": "Salt",
            "strIngredient5": "Squash",
            "strIngredient6": "Broccoli",
            "strIngredient7": "mushrooms",
            "strIngredient8": "Pepper",
            "strIngredient9": "onion",
            "strIngredient10": "garlic",
            "strIngredient11": "red pepper flakes",
            "strIngredient12": "white wine",
            "strIngredient13": "milk",
            "strIngredient14": "heavy cream",
            "strIngredient15": "Parmesan cheese",
            "strIngredient16": "bowtie pasta",
            "strIngredient17": "Salt",
            "strIngredient18": "Pepper",
            "strIngredient19": "Parsley",
            "strIngredient20": "",
            "strMeasure1": "2 tablespoons",
            "strMeasure2": "3 tablespoons",
            "strMeasure3": "5 boneless",
            "strMeasure4": "1 teaspoon",
            "strMeasure5": "1 cut into 1/2-inch cubes",
            "strMeasure6": "1 Head chopped",
            "strMeasure7": "8-ounce sliced",
            "strMeasure8": "1 red",
            "strMeasure9": "1 chopped",
            "strMeasure10": "3 cloves",
            "strMeasure11": "1/2 teaspoon",
            "strMeasure12": "1/2 cup",
            "strMeasure13": "1/2 cup",
            "strMeasure14": "1/2 cup",
            "strMeasure15": "1 cup grated",
            "strMeasure16": "16 ounces",
            "strMeasure17": "pinch",
            "strMeasure18": "pinch ",
            "strMeasure19": "chopped",
            "strMeasure20": "",
            "strSource": "",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        }
    ]
}

[
    {
        "idMeal": "52775",
        "strMeal": "Vegan Lasagna",
        "strMealAlternate": null,
        "strCategory": "Vegan",
        "strArea": "Italian",
        "strInstructions": "1) Preheat oven to 180 degrees celcius. \r\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes. \r\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside. \r\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\r\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish. \r\n6) Bake in the preheated oven for about 25 minutes.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
        "strTags": "Vegan,Pasta",
        "strYoutube": "https://www.youtube.com/watch?v=VU8cXvlGbvc",
        "strIngredient1": "green red lentils",
        "strIngredient2": "Carrots",
        "strIngredient3": "onion",
        "strIngredient4": "zucchini",
        "strIngredient5": "coriander",
        "strIngredient6": "spinach",
        "strIngredient7": "lasagne sheets",
        "strIngredient8": "vegan butter",
        "strIngredient9": "flour",
        "strIngredient10": "soya milk",
        "strIngredient11": "mustard",
        "strIngredient12": "vinegar",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "1 cups",
        "strMeasure2": "1",
        "strMeasure3": "1",
        "strMeasure4": "1 small",
        "strMeasure5": "sprinking",
        "strMeasure6": "150g",
        "strMeasure7": "10",
        "strMeasure8": "35g",
        "strMeasure9": "4 tablespoons",
        "strMeasure10": "300ml",
        "strMeasure11": "1.5 teaspoons",
        "strMeasure12": "1 teaspoon",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": null,
        "strMeasure17": null,
        "strMeasure18": null,
        "strMeasure19": null,
        "strMeasure20": null,
        "strSource": null,
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }
]